name: deadman
targets:
  DeadmanApp:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: 17.0
    settings:
      base:
        SWIFT_VERSION: 5.9
        PRODUCT_BUNDLE_IDENTIFIER: net.terminal-end.deadmanapp
    info:
      path: "./DeadmanApp/Info.plist"
      properties:
        UILaunchScreen:
        UIRequiresFullScreen: YES
    sources:
    - DeadmanApp
    - project.yml
